** Basic syntax

In [2]:
import tensorflow as tf

In [5]:
# Constant

hello=tf.constant("Hello")

In [7]:
# create a session

with tf.Session() as sess:
    result=sess.run(hello)

In [8]:
result
# 'b' represents byte literal

b'Hello'

In [12]:
a=tf.constant(5)
b=tf.constant(5)

In [13]:
with tf.Session() as sess:
    result=sess.run(a+b)

In [14]:
result

10

In [16]:
# Create a matrix

fill_mat=tf.fill((4,4),10)
my_zeros= tf.zeros((4,4))
my_ones= tf.ones((4,4))
myrandn= tf.random_normal((4,4),mean=0,stddev=1.0)
myrandu= tf.random_uniform((4,4),minval=0,maxval=1)

In [18]:
# Interactive session- useful for notebook

sess=tf.InteractiveSession()

In [19]:
sess.run(my_zeros)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [20]:
sess.run(myrandu)

array([[ 0.32858217,  0.67098355,  0.20156384,  0.36465251],
       [ 0.96644652,  0.47540426,  0.33731627,  0.05845106],
       [ 0.56764698,  0.16735601,  0.96940565,  0.30205214],
       [ 0.10618889,  0.30926454,  0.68434191,  0.1555438 ]], dtype=float32)

In [23]:
a=tf.constant([[1,2],[3,4]])

In [24]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [25]:
b=tf.constant([[1,2],[3,4]])

In [26]:
c= tf.matmul(a,b)

In [27]:
sess.run(c)

array([[ 7, 10],
       [15, 22]], dtype=int32)

** Graphs
1. We construct graph and then execute it
2. Can be made in python
3. How to create default graph

In [28]:
n1=tf.constant(1)

In [33]:
n2= tf.constant(2)

In [34]:
n3=n1+n2

In [35]:
sess.run(n3)

3

In [36]:
tf.get_default_graph()

In [38]:
g= tf.Graph()
g

** Variables and Placeholders

variables hold the values of weights and biases throughout the session
variables need to be intialized
placeholder- initially empty
placeholder- used to feed in actual training examples

In [39]:
a= tf.random_uniform((4,4),2)

In [41]:
c=tf.Variable(initial_value=a)

In [50]:
#sess.run(c)
init=tf.global_variables_initializer()

In [51]:
sess.run(init)

In [52]:
sess.run(c)

array([[ 1.54240477,  1.31166899,  1.12264764,  1.18008435],
       [ 1.14770603,  1.14467716,  1.59585774,  1.12717652],
       [ 1.97350442,  1.91180503,  1.48954356,  1.13799453],
       [ 1.32848096,  1.90230083,  1.43154287,  1.56392622]], dtype=float32)

1. create variable
2. initialize using global veriable initializer
3. run initializer
4. run session

In [54]:
ph= tf.placeholder(tf.float32,shape= (None,4))
ph

<tf.Tensor 'Placeholder_1:0' shape=(?, 4) dtype=float32>